module.exports = {
    '--overrides-breadcrumb-color':'rgba(51, 51, 51, .67)',
    '--overrides-p-color': '#74737a',
    '--overrides-a-color': '#a9a9a9',
    '--overrides-a-focus-color': '#a9a9a9',
    '--overrides-h-color': '#86201e',
    '--font-1': 'Roboto Condensed, sans-serif',
    '--font-2': 'Roboto Condensed, sans-serif',
    '--font-3': 'Roboto Condensed, sans-serif',
    '--content-grey-rule-bg-color': '#c7c7c7',
    '--content-a-color': '#3898EC',
    '--content-text-block-color': '#74737a',
    '--content-button-bg-color': 'rgb(250, 162, 28)',
    '--content-button-color': '#fff',
    '--content-tab-pane-bg-color': '#fff',
    '--content-search-result-bg-color': '#fff',
    '--content-search-result-box-shadow': '0 0 0 1px rgba(0, 0, 0, .06)',
    '--content-search-result-color': 'rgba(51, 51, 51, .67)',
    '--content-search-result-h1-color': '#74737a',
    '--content-search-result-span-color': '#434246',
    '--content-search-result-a-color': '#3898EC',
    '--content-search-result-more-color': '#1abc9c',
    '--content-search-result-more-hover-color': '#1abc9c',
    '--content-doc-download-border-color': '#000',
    '--content-breadcrumb-color': 'rgba(51, 51, 51, .67)',
    '--autosuggest-color': '#333333',
    '--home-wbutton-bg-color': 'rgb(250, 162, 28)',
    '--home-more-color': '#fff',
    '--home-more-bg-color': 'rgb(250, 162, 28)',
    '--footer-bg-color': 'rgb(35, 35, 35)',
    '--footer-color': '#dddada',
    '--footer-bg-color2': '#171b1d',
    '--footer-a-color': '#dddada',
    '--footer-submit-bg': 'rgb(250, 162, 28)',
    '--footer-submit-color': '#fff',
    '--footer-social-bg-color': 'white',
    '--footer-social-color': '#010101',
    '--social-img-bg': '#010101',
    '--footer-p-color': '#dddada',
    '--pagecontentcolumn-bg-color': '#fff',
    '--pagecontentcolumn-color': 'rgba(51, 51, 51, .67)',
    '--div-block-2-bg-color': '#000',
    '--div-block-4-bg-color': '#1abc9c',
    '--div-block-5-bg-color': '#f2ca27',
    '--div-block-6-bg-color': '#e67e22',
    '--div-block-7-bg-color': '#16a085',
    '--div-block-8-bg-color': '#2980b9',
    '--div-block-9-bg-color': '#e74c3c',
    '--div-block-10-bg-color': '#1abc9c',
    '--paginator-li-bg-color': 'rgb(250, 162, 28)',
    '--paginator-li-border-color': 'rgb(250, 162, 28)',
    '--paginator-li-color': '#20577d',
    '--paginator-li-disabled-color': '#777',
    '--paginator-li-disabled-border-color': '#ddd',
    '--reacttabs-bg-color': 'linear-gradient(to bottom, #2d2d2d 0%,#2b2b2b 30%,#292929 51%,#272727 75%,#252525 100%)',
    '--reacttabs-color': '#fff!important',
    '--reacttabs-selected-bg-color': 'linear-gradient(to bottom, #2d2d2d 0%,#2b2b2b 30%,#292929 51%,#272727 75%,#252525 100%)',
    '--reacttabs-selected-color': 'rgb(250, 162, 28)',
    '--reacttabs-border': '0px !important',
    '--reacttabs-border-radius': '0px !important',
    '--reacttabs-bg-image': '#2d2d2d url(./assets/main-divider.jpg) no-repeat center right',
    '--reacttabs-hover-bg-color': 'black',
    '--reacttabs-hover-color': '#f9a11b',
    '--recentdocs-bg-color': 'white',
    '--section-bg-color': '#86201e', /* SIG */
    '--section-color': 'rgb(250, 162, 28)',
    '--sidebar-footer-color': '#aaa',
    '--sidebar-a-color': '#a9a9a9',
    '--sidebar-bg-color': '#fff',
    '--sidebar-box-shadow': '0 0 0 1px rgba(0, 0, 0, .06)',
    '--sidebar-border-radius': '0px',
    '--sitesearch-color': '#74737a',
    '--sitesearc-li-bg-color': 'rgb(250, 244, 244) !important',
    '--sitesearch-li-color': '#a9a9a9', 
    '--sitesearch-bg-image': 'radial-gradient(circle, black, black 7%, transparent 15%, transparent 35%, black 45%, black 48%, transparent 55%)',
    '--sitesearch-loading-bg-image': 'url("http://loadinggif.com/images/image-selection/3.gif")',
    '--sitesearch-loading-bg-color': '#ffffff',
    '--topbar-bg': 'white',
    '--topbar-submit-button-bg-color': 'rgb(250, 162, 28)',
    '--topbar-box-shadow':  '0 1px 0 0 rgba(0, 0, 0, .06)',
    '--logo-img': 'url("themes/default/assets/logo.png")',
    '--logo-color': '#231f20',
    '--logo-color2': '#90292a',
    '--languageswitcher-highlight-bg-color': 'rgb(51, 51, 51)',
    '--languageswitcher-bg-color': 'rgb(51, 51, 51)',
    '--languageswitcher-color': '#a9a9a9',    
}